package dumpUI3.components.globalslavepanel;


	import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import dumpUI3.model.entity.Report;


	

	/**
	 *
	 * @author mjcobo
	 */
	public class WordGlobalSlavePanel extends GlobalSlavePanel<Report> {

	  /** Creates new form WordGlobalSlavePanel */
	  public WordGlobalSlavePanel() {
	    initComponents();
	  }

	  @Override
	  public void refresh(Report item) {

	    setMasterItem(item);
/*
	    this.wordDetailPanel.refreshItem(item);
	    this.wordSlaveWordGroupPanel.setMasterItem(item);
	    this.wordSlaveDocumentsPanel.setMasterItem(item);
*/
	    if (item != null) {
	      
	      this.updateWordButton.setEnabled(true);

	    } else {
	      
	      this.updateWordButton.setEnabled(false);

	    }
	  }

	  /** This method is called from within the constructor to
	   * initialize the form.
	   * WARNING: Do NOT modify this code. The content of this method is
	   * always regenerated by the Form Editor.
	   */
	  @SuppressWarnings("unchecked")
	  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	  private void initComponents() {
		  wordInfoPanel = new JPanel();
/*
	    hideAndShowWordPanel = new scimat.gui.components.HideAndShowPanel();
	   
	    updateWordButton = new javax.swing.JButton();
	    wordDetailPanel = new scimat.gui.components.detailspanel.WordDetailPanel();
	    hideAndShowWordGroupPanel = new scimat.gui.components.HideAndShowPanel();
	    this.hideAndShowWordGroupPanel.setDescription("Report group info");
	    this.hideAndShowWordGroupPanel.setPanel(this.wordSlaveWordGroupPanel);
	    wordGroupInfoPanel = new javax.swing.JPanel();
	    wordSlaveWordGroupPanel = new scimat.gui.components.slavepanel.WordSlaveWordGroupPanel();
	    hideAndShowDocumentPanel = new scimat.gui.components.HideAndShowPanel();
	    documentInfoPanel = new javax.swing.JPanel();
	   wordSlaveDocumentsPanel = new scimat.gui.components.slavepanel.WordSlaveDocumentsPanel();
*/
	   // this.hideAndShowWordPanel.setDescription("Report info");
	  //  this.hideAndShowWordPanel.setPanel(this.wordInfoPanel);

	   // updateWordButton.setText("Update");
	  //  updateWordButton.addActionListener(new java.awt.event.ActionListener() {
/*	      public void actionPerformed(java.awt.event.ActionEvent evt) {
	        updateWordButtonActionPerformed(evt);
	      }
	    });
*/
	    javax.swing.GroupLayout wordInfoPanelLayout = new GroupLayout(wordInfoPanel);
	    wordInfoPanel.setLayout(wordInfoPanelLayout);
	/*    wordInfoPanelLayout.setHorizontalGroup(
	      wordInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wordInfoPanelLayout.createSequentialGroup()
	        .addContainerGap(313, Short.MAX_VALUE)
	        .addComponent(updateWordButton))
	      .addComponent(wordDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
	    );
	    wordInfoPanelLayout.setVerticalGroup(
	      wordInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wordInfoPanelLayout.createSequentialGroup()
	        .addComponent(wordDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	        .addComponent(updateWordButton))
	    );

	    javax.swing.GroupLayout wordGroupInfoPanelLayout = new javax.swing.GroupLayout(wordGroupInfoPanel);
	    wordGroupInfoPanel.setLayout(wordGroupInfoPanelLayout);
	    wordGroupInfoPanelLayout.setHorizontalGroup(
	      wordGroupInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	      .addComponent(wordSlaveWordGroupPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
	    );
	    wordGroupInfoPanelLayout.setVerticalGroup(
	      wordGroupInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	      .addComponent(wordSlaveWordGroupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	    );

	    this.hideAndShowDocumentPanel.setDescription("Documents info");
	    this.hideAndShowDocumentPanel.setPanel(this.wordSlaveDocumentsPanel);

	    javax.swing.GroupLayout documentInfoPanelLayout = new javax.swing.GroupLayout(documentInfoPanel);
	    documentInfoPanel.setLayout(documentInfoPanelLayout);
	    documentInfoPanelLayout.setHorizontalGroup(
	      documentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	      .addComponent(wordSlaveDocumentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
	    );
	    documentInfoPanelLayout.setVerticalGroup(
	      documentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	      .addComponent(wordSlaveDocumentsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
	    );
*/
	    GroupLayout layout = new GroupLayout(this);
	    this.setLayout(layout);
	   /* layout.setHorizontalGroup(
	      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	      .addGroup(layout.createSequentialGroup()
	        .addContainerGap()
	        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	          .addComponent(wordGroupInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	          .addComponent(wordInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	          .addComponent(hideAndShowWordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
	          .addComponent(hideAndShowWordGroupPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
	          .addComponent(hideAndShowDocumentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	          .addComponent(documentInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	        .addContainerGap())
	    );*/
	   /* layout.setVerticalGroup(
	      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	      .addGroup(layout.createSequentialGroup()
	        .addComponent(hideAndShowWordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	        .addComponent(wordInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	        .addComponent(hideAndShowWordGroupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	        .addComponent(wordGroupInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	        .addComponent(hideAndShowDocumentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	        .addComponent(documentInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	        .addContainerGap())
	    );*/
	  }// </editor-fold>//GEN-END:initComponents

	 
	
	  private JPanel documentInfoPanel;
	  
	  private JButton updateWordButton;
	  
	  private JPanel wordGroupInfoPanel;
	  private JPanel wordInfoPanel;
	  
	  // End of variables declaration//GEN-END:variables
	}